package br.sp.senac.tads.views;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class TelaClientes extends javax.swing.JFrame {

    public TelaClientes() {
        initComponents();
        desabilitado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdoGrupoPesquisa = new javax.swing.ButtonGroup();
        pnlFundo = new javax.swing.JPanel();
        pnlBarraLateral = new javax.swing.JPanel();
        lblIconeUsuario = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        btnProdutos = new javax.swing.JPanel();
        lblIconeProdutos = new javax.swing.JLabel();
        lblProdutos = new javax.swing.JLabel();
        btnClientes = new javax.swing.JPanel();
        lblIconeClientes = new javax.swing.JLabel();
        lblClientes = new javax.swing.JLabel();
        btnRelatorios = new javax.swing.JPanel();
        lblIconeRelatorios = new javax.swing.JLabel();
        lblRelatorios = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JPanel();
        lblLimpar = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JPanel();
        lblVoltar = new javax.swing.JLabel();
        lblFechar = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblPesquisarPor = new javax.swing.JLabel();
        rdoNome = new javax.swing.JRadioButton();
        rdoCPF = new javax.swing.JRadioButton();
        lblNome = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCPF = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsulta = new javax.swing.JTable();
        btnCadastrar = new javax.swing.JPanel();
        lblIconeCadastrar = new javax.swing.JLabel();
        lblCadastrar = new javax.swing.JLabel();
        btnEditar = new javax.swing.JPanel();
        lblIconeEditar = new javax.swing.JLabel();
        lblEditar = new javax.swing.JLabel();
        btnRemover = new javax.swing.JPanel();
        lblIconeRemover = new javax.swing.JLabel();
        lblRemover = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JPanel();
        lblIconePesquisar = new javax.swing.JLabel();
        lblPesquisar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFundo.setBackground(new java.awt.Color(255, 255, 255));
        pnlFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBarraLateral.setBackground(new java.awt.Color(0, 85, 166));
        pnlBarraLateral.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        pnlBarraLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconeUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilitarios/user.png"))); // NOI18N
        pnlBarraLateral.add(lblIconeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 40, 40));

        lblUsuario.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("ADMIN");
        pnlBarraLateral.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 8, -1, 40));

        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilitarios/logout.png"))); // NOI18N
        lblLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });
        pnlBarraLateral.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        btnProdutos.setBackground(new java.awt.Color(0, 85, 166));
        btnProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProdutosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProdutosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProdutosMouseExited(evt);
            }
        });
        btnProdutos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconeProdutos.setForeground(new java.awt.Color(255, 255, 255));
        lblIconeProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilitarios/produtosIcon.png"))); // NOI18N
        btnProdutos.add(lblIconeProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        lblProdutos.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        lblProdutos.setForeground(new java.awt.Color(255, 255, 255));
        lblProdutos.setText("Produtos");
        btnProdutos.add(lblProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 130, -1));

        pnlBarraLateral.add(btnProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 220, 50));

        btnClientes.setBackground(new java.awt.Color(40, 40, 40));
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconeClientes.setForeground(new java.awt.Color(255, 255, 255));
        lblIconeClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilitarios/clientesIcon.png"))); // NOI18N
        btnClientes.add(lblIconeClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        lblClientes.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        lblClientes.setForeground(new java.awt.Color(255, 255, 255));
        lblClientes.setText("Clientes");
        btnClientes.add(lblClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 130, -1));

        pnlBarraLateral.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 220, 50));

        btnRelatorios.setBackground(new java.awt.Color(0, 85, 166));
        btnRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRelatoriosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRelatoriosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRelatoriosMouseExited(evt);
            }
        });
        btnRelatorios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconeRelatorios.setForeground(new java.awt.Color(255, 255, 255));
        lblIconeRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilitarios/relatoriosIcon.png"))); // NOI18N
        btnRelatorios.add(lblIconeRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        lblRelatorios.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        lblRelatorios.setForeground(new java.awt.Color(255, 255, 255));
        lblRelatorios.setText("Relatórios");
        btnRelatorios.add(lblRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 130, -1));

        pnlBarraLateral.add(btnRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 220, 50));

        pnlFundo.add(pnlBarraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 600));

        btnLimpar.setBackground(new java.awt.Color(0, 85, 166));
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimparMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimparMouseExited(evt);
            }
        });
        btnLimpar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLimpar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblLimpar.setForeground(new java.awt.Color(255, 255, 255));
        lblLimpar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLimpar.setText("Limpar");
        btnLimpar.add(lblLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        pnlFundo.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 90, 40));

        btnVoltar.setBackground(new java.awt.Color(0, 85, 166));
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarMouseExited(evt);
            }
        });
        btnVoltar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVoltar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblVoltar.setForeground(new java.awt.Color(255, 255, 255));
        lblVoltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVoltar.setText("Voltar");
        btnVoltar.add(lblVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        pnlFundo.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 90, 40));

        lblFechar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        lblFechar.setForeground(new java.awt.Color(40, 40, 40));
        lblFechar.setText("X");
        lblFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharMouseClicked(evt);
            }
        });
        pnlFundo.add(lblFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        lblMinimizar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        lblMinimizar.setForeground(new java.awt.Color(40, 40, 40));
        lblMinimizar.setText("_");
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });
        pnlFundo.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, -1));

        lblPesquisarPor.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblPesquisarPor.setForeground(new java.awt.Color(40, 40, 40));
        lblPesquisarPor.setText("Pesquisar por:");
        pnlFundo.add(lblPesquisarPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        rdoNome.setBackground(new java.awt.Color(255, 255, 255));
        rdoGrupoPesquisa.add(rdoNome);
        rdoNome.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        rdoNome.setText("Nome");
        rdoNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoNomeMouseClicked(evt);
            }
        });
        rdoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNomeActionPerformed(evt);
            }
        });
        pnlFundo.add(rdoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        rdoCPF.setBackground(new java.awt.Color(255, 255, 255));
        rdoGrupoPesquisa.add(rdoCPF);
        rdoCPF.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        rdoCPF.setText("CPF");
        rdoCPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdoCPFMouseClicked(evt);
            }
        });
        pnlFundo.add(rdoCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        lblNome.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(40, 40, 40));
        lblNome.setText("Nome");
        pnlFundo.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 60, -1));

        lblCPF.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(40, 40, 40));
        lblCPF.setText("CPF");
        pnlFundo.add(lblCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 40, -1));

        txtNome.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtNome.setForeground(new java.awt.Color(40, 40, 40));
        txtNome.setBorder(null);
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });
        pnlFundo.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 280, -1));

        txtCPF.setBorder(null);
        txtCPF.setForeground(new java.awt.Color(40, 40, 40));
        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        pnlFundo.add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 190, -1));
        pnlFundo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 280, 10));
        pnlFundo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 190, 10));

        tblConsulta.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        tblConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Sexo"
            }
        ));
        tblConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblConsulta.setGridColor(new java.awt.Color(40, 40, 40));
        tblConsulta.setSelectionBackground(new java.awt.Color(0, 85, 166));
        jScrollPane1.setViewportView(tblConsulta);
        if (tblConsulta.getColumnModel().getColumnCount() > 0) {
            tblConsulta.getColumnModel().getColumn(0).setResizable(false);
            tblConsulta.getColumnModel().getColumn(1).setResizable(false);
            tblConsulta.getColumnModel().getColumn(2).setResizable(false);
        }

        pnlFundo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 500, 250));

        btnCadastrar.setBackground(new java.awt.Color(0, 85, 166));
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseExited(evt);
            }
        });
        btnCadastrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconeCadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconeCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilitarios/add.png"))); // NOI18N
        btnCadastrar.add(lblIconeCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        lblCadastrar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        lblCadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadastrar.setText("Cadastrar");
        btnCadastrar.add(lblCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 50, 70, -1));

        pnlFundo.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 80, 70));

        btnEditar.setBackground(new java.awt.Color(0, 85, 166));
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });
        btnEditar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconeEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconeEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilitarios/editarIcon.png"))); // NOI18N
        btnEditar.add(lblIconeEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        lblEditar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblEditar.setForeground(new java.awt.Color(255, 255, 255));
        lblEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditar.setText("Editar");
        btnEditar.add(lblEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 50, 70, -1));

        pnlFundo.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 80, 70));

        btnRemover.setBackground(new java.awt.Color(0, 85, 166));
        btnRemover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRemoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRemoverMouseExited(evt);
            }
        });
        btnRemover.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconeRemover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconeRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilitarios/removerIcon.png"))); // NOI18N
        btnRemover.add(lblIconeRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        lblRemover.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblRemover.setForeground(new java.awt.Color(255, 255, 255));
        lblRemover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRemover.setText("Remover");
        btnRemover.add(lblRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 50, 70, -1));

        pnlFundo.add(btnRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 80, 70));

        btnPesquisar.setBackground(new java.awt.Color(0, 85, 166));
        btnPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseExited(evt);
            }
        });
        btnPesquisar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconePesquisar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconePesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilitarios/lupa.png"))); // NOI18N
        btnPesquisar.add(lblIconePesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        lblPesquisar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        lblPesquisar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPesquisar.setText("Pesquisar");
        btnPesquisar.add(lblPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 50, 70, -1));

        pnlFundo.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 80, 70));

        getContentPane().add(pnlFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdutosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutosMouseEntered
        setColor(btnProdutos);
    }//GEN-LAST:event_btnProdutosMouseEntered

    private void btnProdutosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutosMouseExited
        resetColor(btnProdutos);
    }//GEN-LAST:event_btnProdutosMouseExited

    private void btnRelatoriosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatoriosMouseEntered
        setColor(btnRelatorios);
    }//GEN-LAST:event_btnRelatoriosMouseEntered

    private void btnRelatoriosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatoriosMouseExited
        resetColor(btnRelatorios);
    }//GEN-LAST:event_btnRelatoriosMouseExited

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        this.setState(1);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void btnVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseEntered
        setColor(btnVoltar);
    }//GEN-LAST:event_btnVoltarMouseEntered

    private void btnVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseExited
        resetColor(btnVoltar);
    }//GEN-LAST:event_btnVoltarMouseExited

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        //VOLTAR PARA O MENU PRINCIPAL
        new TelaMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarMouseClicked

    private void lblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseClicked
        //VOLTAR PARA O MENU PRINCIPAL
        new TelaMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblFecharMouseClicked

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        //VOLTAR PARA A TELA DE LOGIN
        new TelaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void btnCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseEntered
        setColor(btnCadastrar);
    }//GEN-LAST:event_btnCadastrarMouseEntered

    private void btnCadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseExited
        resetColor(btnCadastrar);
    }//GEN-LAST:event_btnCadastrarMouseExited

    private void btnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseEntered
        setColor(btnEditar);
    }//GEN-LAST:event_btnEditarMouseEntered

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        resetColor(btnEditar);
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnRemoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoverMouseEntered
        setColor(btnRemover);
    }//GEN-LAST:event_btnRemoverMouseEntered

    private void btnRemoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoverMouseExited
        resetColor(btnRemover);
    }//GEN-LAST:event_btnRemoverMouseExited

    private void btnPesquisarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseEntered
        setColor(btnPesquisar);
    }//GEN-LAST:event_btnPesquisarMouseEntered

    private void btnPesquisarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseExited
        resetColor(btnPesquisar);
    }//GEN-LAST:event_btnPesquisarMouseExited

    private void btnRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoverMouseClicked
        // TODO add your handling code here:
        //resgata o indice da linha selecionada
        int linhaSelecionada = tblConsulta.getSelectedRow();
        if (linhaSelecionada >= 0) {
            int result = JOptionPane.showConfirmDialog(this, "Deseja exluir o cliente selecionado?", "Excluir", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                DefaultTableModel clientes = new DefaultTableModel();
                clientes = (DefaultTableModel) tblConsulta.getModel();
                clientes.removeRow(linhaSelecionada);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um cliente!", "Erro!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoverMouseClicked

    private void btnLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseClicked
        limparCampos();
    }//GEN-LAST:event_btnLimparMouseClicked

    private void btnLimparMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseEntered
        setColor(btnLimpar);
    }//GEN-LAST:event_btnLimparMouseEntered

    private void btnLimparMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseExited
        resetColor(btnLimpar);
    }//GEN-LAST:event_btnLimparMouseExited

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        int linhaSelecionada = tblConsulta.getSelectedRow();

        if (linhaSelecionada >= 0) {
            //ACESSA A TELA DE EDITAR CLIENTE
            new TelaClientesEditar().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Cliente", "Erro!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarMouseClicked
    private void rdoNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoNomeMouseClicked
        if (rdoNome.isSelected()) {
            habilitado();
        }
    }//GEN-LAST:event_rdoNomeMouseClicked
    private void btnPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseClicked
        if (validarFormulario()) {

        }
    }//GEN-LAST:event_btnPesquisarMouseClicked

    private void rdoCPFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdoCPFMouseClicked
        if (rdoCPF.isSelected()) {
            habilitado();
        }
    }//GEN-LAST:event_rdoCPFMouseClicked

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
        // TODO add your handling code here:
        if (txtNome.getText().length() < 30) {
            if (txtNome.getText().matches("^[0-9].*")) {
                evt.consume();
                JOptionPane.showMessageDialog(this, "Permitido somente letras no campo \"Nome\"!");
            }
        } else {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Limite de até 30 caracteres.");
        }
    }//GEN-LAST:event_txtNomeKeyTyped
    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        //ACESSA A TELA DE CADASTRO DE CLIENTES
        new TelaClientesCadastro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastrarMouseClicked

    private void btnProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutosMouseClicked
        //ACESSA A TELA PRODUTOS
        new TelaProdutos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProdutosMouseClicked

    private void btnRelatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatoriosMouseClicked
        //ACESSA A TELA DE RELATÓRIOS
        new TelaRelatorios().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRelatoriosMouseClicked

    private void rdoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNomeActionPerformed

    }//GEN-LAST:event_rdoNomeActionPerformed

    //ALTERAR A COR DO OBJETO AO PASSAR O MOUSE
    public void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(40, 40, 40));
    }

    //VOLTAR PARA A COR PADRÃO DO OBJETO AO TIRAR O MOUSE DE CIMA
    public void resetColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(0, 85, 166));
    }

    private boolean desabilitado() {
        btnCadastrar.setEnabled(false);
        txtCPF.setEnabled(false);
        txtNome.setEnabled(false);
        btnEditar.setEnabled(false);
        btnRemover.setEnabled(false);
        btnPesquisar.setEnabled(false);
        btnLimpar.setEnabled(false);
        return false;
    }

    private void habilitado() {
        if (rdoNome.isSelected()) {
            txtCPF.setEnabled(false);
            txtNome.setEnabled(true);
            btnEditar.setEnabled(true);
            btnRemover.setEnabled(true);
            btnPesquisar.setEnabled(true);
            btnLimpar.setEnabled(true);
        } else if (rdoCPF.isSelected()) {
            txtNome.setEnabled(false);
            txtCPF.setEnabled(true);
            btnEditar.setEnabled(true);
            btnRemover.setEnabled(true);
            btnPesquisar.setEnabled(true);
            btnLimpar.setEnabled(true);
        }
    }

    private boolean validarFormulario() {

        if (rdoNome.isSelected() == false && rdoCPF.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "Selecione uma opção de busca!", "Erro!", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (rdoNome.isSelected() && txtNome.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "O campo \"Nome\" está vazio!");
            return false;
        }
        if (rdoCPF.isSelected() && this.txtCPF.getText().equals("   .   .   -  ")) {
            JOptionPane.showMessageDialog(this, "O campo \"CPF\" está vazio");
            return false;
        }
        return true;
    }

    //Função limpar para limpar campos
    private void limparCampos() {
        txtNome.setText("");
        txtCPF.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCadastrar;
    private javax.swing.JPanel btnClientes;
    private javax.swing.JPanel btnEditar;
    private javax.swing.JPanel btnLimpar;
    private javax.swing.JPanel btnPesquisar;
    private javax.swing.JPanel btnProdutos;
    private javax.swing.JPanel btnRelatorios;
    private javax.swing.JPanel btnRemover;
    private javax.swing.JPanel btnVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCadastrar;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblFechar;
    private javax.swing.JLabel lblIconeCadastrar;
    private javax.swing.JLabel lblIconeClientes;
    private javax.swing.JLabel lblIconeEditar;
    private javax.swing.JLabel lblIconePesquisar;
    private javax.swing.JLabel lblIconeProdutos;
    private javax.swing.JLabel lblIconeRelatorios;
    private javax.swing.JLabel lblIconeRemover;
    private javax.swing.JLabel lblIconeUsuario;
    private javax.swing.JLabel lblLimpar;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JLabel lblPesquisarPor;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JLabel lblRelatorios;
    private javax.swing.JLabel lblRemover;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblVoltar;
    private javax.swing.JPanel pnlBarraLateral;
    private javax.swing.JPanel pnlFundo;
    private javax.swing.JRadioButton rdoCPF;
    private javax.swing.ButtonGroup rdoGrupoPesquisa;
    private javax.swing.JRadioButton rdoNome;
    private javax.swing.JTable tblConsulta;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
