package br.sp.senac.tads.views;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class TelaVendas extends javax.swing.JFrame {

    public TelaVendas() {
        initComponents();
        this.txtQtdEstoque.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFundo = new javax.swing.JPanel();
        pnlBarraTitulo = new javax.swing.JPanel();
        lblFechar = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblNovaVenda = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JPanel();
        lblCancelar = new javax.swing.JLabel();
        btnConcluir = new javax.swing.JPanel();
        lblConcluir = new javax.swing.JLabel();
        pnlClientes = new javax.swing.JPanel();
        lblNomeCli = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnConfirmar = new javax.swing.JPanel();
        lblConfirmar = new javax.swing.JLabel();
        pnlProdutos = new javax.swing.JPanel();
        lblProduto = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblQtdEstoque = new javax.swing.JLabel();
        txtQtdEstoque = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblQtd = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        btnPesquisar = new javax.swing.JPanel();
        lblPesquisar = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JPanel();
        lblLimpar = new javax.swing.JLabel();
        btnInserir = new javax.swing.JPanel();
        lblInserir = new javax.swing.JLabel();
        pnlItens = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItens = new javax.swing.JTable();
        lblCompra = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFundo.setBackground(new java.awt.Color(255, 255, 255));
        pnlFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBarraTitulo.setBackground(new java.awt.Color(0, 85, 166));
        pnlBarraTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFechar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        lblFechar.setForeground(new java.awt.Color(255, 255, 255));
        lblFechar.setText("X");
        lblFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharMouseClicked(evt);
            }
        });
        pnlBarraTitulo.add(lblFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        lblMinimizar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        lblMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimizar.setText("_");
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });
        pnlBarraTitulo.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, -1));

        lblNovaVenda.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        lblNovaVenda.setForeground(new java.awt.Color(255, 255, 255));
        lblNovaVenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNovaVenda.setText("Nova venda");
        pnlBarraTitulo.add(lblNovaVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 40));

        pnlFundo.add(pnlBarraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        btnCancelar.setBackground(new java.awt.Color(0, 85, 166));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        btnCancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCancelar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblCancelar.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancelar.setText("Cancelar");
        btnCancelar.add(lblCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 20));

        pnlFundo.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 540, 90, 40));

        btnConcluir.setBackground(new java.awt.Color(0, 85, 166));
        btnConcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConcluirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConcluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConcluirMouseExited(evt);
            }
        });
        btnConcluir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblConcluir.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblConcluir.setForeground(new java.awt.Color(255, 255, 255));
        lblConcluir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConcluir.setText("Concluir");
        btnConcluir.add(lblConcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        pnlFundo.add(btnConcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 90, 40));

        pnlClientes.setBackground(new java.awt.Color(255, 255, 255));
        pnlClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 40), 1, true), "Selecione o cliente", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 0, 18))); // NOI18N
        pnlClientes.setForeground(new java.awt.Color(40, 40, 40));
        pnlClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomeCli.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblNomeCli.setForeground(new java.awt.Color(40, 40, 40));
        lblNomeCli.setText("Nome do cliente");
        pnlClientes.add(lblNomeCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtCliente.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtCliente.setForeground(new java.awt.Color(40, 40, 40));
        txtCliente.setBorder(null);
        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClienteKeyTyped(evt);
            }
        });
        pnlClientes.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 310, -1));
        pnlClientes.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 310, 10));

        btnConfirmar.setBackground(new java.awt.Color(0, 85, 166));
        btnConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseExited(evt);
            }
        });
        btnConfirmar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblConfirmar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfirmar.setText("Confirmar");
        btnConfirmar.add(lblConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 20));

        pnlClientes.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 90, 40));

        pnlFundo.add(pnlClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 350, 150));

        pnlProdutos.setBackground(new java.awt.Color(255, 255, 255));
        pnlProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 40), 1, true), "Produtos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 0, 18), new java.awt.Color(40, 40, 40))); // NOI18N
        pnlProdutos.setForeground(new java.awt.Color(40, 40, 40));
        pnlProdutos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProduto.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblProduto.setForeground(new java.awt.Color(40, 40, 40));
        lblProduto.setText("Produto");
        pnlProdutos.add(lblProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtProduto.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtProduto.setForeground(new java.awt.Color(40, 40, 40));
        txtProduto.setBorder(null);
        pnlProdutos.add(txtProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 310, -1));
        pnlProdutos.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 310, 10));

        lblQtdEstoque.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblQtdEstoque.setForeground(new java.awt.Color(40, 40, 40));
        lblQtdEstoque.setText("Quantidade em estoque");
        pnlProdutos.add(lblQtdEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        txtQtdEstoque.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtQtdEstoque.setForeground(new java.awt.Color(40, 40, 40));
        txtQtdEstoque.setBorder(null);
        pnlProdutos.add(txtQtdEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 310, -1));
        pnlProdutos.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 310, 10));

        lblQtd.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblQtd.setForeground(new java.awt.Color(40, 40, 40));
        lblQtd.setText("Quantidade");
        pnlProdutos.add(lblQtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txtQtd.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtQtd.setForeground(new java.awt.Color(40, 40, 40));
        txtQtd.setBorder(null);
        txtQtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtdKeyTyped(evt);
            }
        });
        pnlProdutos.add(txtQtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 310, -1));
        pnlProdutos.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 310, 10));

        btnPesquisar.setBackground(new java.awt.Color(0, 85, 166));
        btnPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseExited(evt);
            }
        });
        btnPesquisar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPesquisar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        lblPesquisar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPesquisar.setText("Pesquisar");
        btnPesquisar.add(lblPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 20));

        pnlProdutos.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 90, 40));

        btnLimpar.setBackground(new java.awt.Color(0, 85, 166));
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimparMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimparMouseExited(evt);
            }
        });
        btnLimpar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLimpar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblLimpar.setForeground(new java.awt.Color(255, 255, 255));
        lblLimpar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLimpar.setText("Limpar");
        btnLimpar.add(lblLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 20));

        pnlProdutos.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, 40));

        btnInserir.setBackground(new java.awt.Color(0, 85, 166));
        btnInserir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInserirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInserirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInserirMouseExited(evt);
            }
        });
        btnInserir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInserir.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblInserir.setForeground(new java.awt.Color(255, 255, 255));
        lblInserir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInserir.setText("Inserir");
        btnInserir.add(lblInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 20));

        pnlProdutos.add(btnInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, 40));

        pnlFundo.add(pnlProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 350, 280));

        pnlItens.setBackground(new java.awt.Color(255, 255, 255));
        pnlItens.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 40), 1, true), "Itens", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 0, 18))); // NOI18N
        pnlItens.setForeground(new java.awt.Color(40, 40, 40));
        pnlItens.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblItens.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        tblItens.setForeground(new java.awt.Color(40, 40, 40));
        tblItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome Produto", "Qtd", "Valor Unit.", "Total"
            }
        ));
        tblItens.setGridColor(new java.awt.Color(40, 40, 40));
        tblItens.setSelectionBackground(new java.awt.Color(0, 85, 166));
        jScrollPane1.setViewportView(tblItens);
        if (tblItens.getColumnModel().getColumnCount() > 0) {
            tblItens.getColumnModel().getColumn(0).setResizable(false);
            tblItens.getColumnModel().getColumn(1).setResizable(false);
            tblItens.getColumnModel().getColumn(3).setResizable(false);
        }

        pnlItens.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 380, 410));

        pnlFundo.add(pnlItens, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 400, 440));

        lblCompra.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        lblCompra.setForeground(new java.awt.Color(40, 40, 40));
        lblCompra.setText("Valor total da compra:");
        pnlFundo.add(lblCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        lblValorTotal.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        lblValorTotal.setForeground(new java.awt.Color(40, 40, 40));
        lblValorTotal.setText("R$ 0,00");
        pnlFundo.add(lblValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, -1, -1));

        getContentPane().add(pnlFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConcluirMouseEntered
        setColor(btnConcluir);
    }//GEN-LAST:event_btnConcluirMouseEntered

    private void btnConcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConcluirMouseExited
        resetColor(btnConcluir);
    }//GEN-LAST:event_btnConcluirMouseExited

    private void lblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseClicked
        //VOLTAR PARA O MENU PRINCIPAL
        new TelaMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblFecharMouseClicked

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        setColor(btnCancelar);
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        resetColor(btnCancelar);
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnConcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConcluirMouseClicked
        ValidarProduto();
        ValidarCliente();
    }//GEN-LAST:event_btnConcluirMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        //VOLTAR PARA O MENU PRINCIPAL
        new TelaMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        this.setState(1);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void btnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseClicked
        ValidarCliente();
    }//GEN-LAST:event_btnConfirmarMouseClicked

    private void btnConfirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseEntered
        setColor(btnConfirmar);
    }//GEN-LAST:event_btnConfirmarMouseEntered

    private void btnConfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseExited
        resetColor(btnConfirmar);
    }//GEN-LAST:event_btnConfirmarMouseExited

    private void btnPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseClicked
        ValidarProduto();
    }//GEN-LAST:event_btnPesquisarMouseClicked

    private void btnPesquisarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseEntered
        setColor(btnPesquisar);
    }//GEN-LAST:event_btnPesquisarMouseEntered

    private void btnPesquisarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseExited
        resetColor(btnPesquisar);
    }//GEN-LAST:event_btnPesquisarMouseExited

    private void btnLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseClicked
        limpar();
    }//GEN-LAST:event_btnLimparMouseClicked

    private void btnLimparMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseEntered
        setColor(btnLimpar);
    }//GEN-LAST:event_btnLimparMouseEntered

    private void btnLimparMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseExited
        resetColor(btnLimpar);
    }//GEN-LAST:event_btnLimparMouseExited

    private void btnInserirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInserirMouseClicked
        ValidarProduto();
    }//GEN-LAST:event_btnInserirMouseClicked

    private void btnInserirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInserirMouseEntered
        setColor(btnInserir);
    }//GEN-LAST:event_btnInserirMouseEntered

    private void btnInserirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInserirMouseExited
        resetColor(btnInserir);
    }//GEN-LAST:event_btnInserirMouseExited

    private void txtClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyTyped
        //Se o nome digitado for menor que 50
        if (txtCliente.getText().length() < 50) {
            //verifica se foi digitado número
            if (txtCliente.getText().matches("^[0-9].*")) {
                evt.consume();
                //caso tenha sido número, retorna que não é permitido número no campo
                JOptionPane.showMessageDialog(this, "Não é permitido números neste campo",
                        "Erro", JOptionPane.ERROR_MESSAGE);
                txtCliente.setText("");
            }
        } else {
            //caso seja maior, estoura o limite de caracteres
            evt.consume();
            JOptionPane.showMessageDialog(this, "Limite de caractere em 50", "Erro", JOptionPane.ERROR_MESSAGE);
            txtCliente.setText("");
        }
    }//GEN-LAST:event_txtClienteKeyTyped

    private void txtQtdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdKeyTyped
        // VALIDAÇÃO QUANTIDADE
        if (txtQtd.getText().length() < 5) {
            String caracteres = "0987654321";
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        } else {
            //caso seja maior, estoura o limite de caracteres
            evt.consume();
            JOptionPane.showMessageDialog(this, "Limite de caractere em 5", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtQtdKeyTyped

    //ALTERAR A COR DO OBJETO AO PASSAR O MOUSE
    public void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(40, 40, 40));
    }

    //VOLTAR PARA A COR PADRÃO DO OBJETO AO TIRAR O MOUSE DE CIMA
    public void resetColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(0, 85, 166));
    }

    private boolean ValidarCliente() {
        if (this.txtCliente.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Campo Nome do Cliente é obrigatório.");
            return false;
        }
        return true;
    }

    private boolean ValidarProduto() {
        if (this.txtProduto.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Campo Produto é obrigatório.");
            return false;
        }
        if (this.txtQtd.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "A quantidade deve ser informada.");
            return false;
        }
        return true;
    }
    
    private void limpar(){
        this.txtProduto.setText("");
        this.txtQtd.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JPanel btnConcluir;
    private javax.swing.JPanel btnConfirmar;
    private javax.swing.JPanel btnInserir;
    private javax.swing.JPanel btnLimpar;
    private javax.swing.JPanel btnPesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblCompra;
    private javax.swing.JLabel lblConcluir;
    private javax.swing.JLabel lblConfirmar;
    private javax.swing.JLabel lblFechar;
    private javax.swing.JLabel lblInserir;
    private javax.swing.JLabel lblLimpar;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblNomeCli;
    private javax.swing.JLabel lblNovaVenda;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblQtd;
    private javax.swing.JLabel lblQtdEstoque;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JPanel pnlBarraTitulo;
    private javax.swing.JPanel pnlClientes;
    private javax.swing.JPanel pnlFundo;
    private javax.swing.JPanel pnlItens;
    private javax.swing.JPanel pnlProdutos;
    private javax.swing.JTable tblItens;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JTextField txtQtdEstoque;
    // End of variables declaration//GEN-END:variables
}
