package br.sp.senac.tads.views;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author JefersonOliveira
 */
public class TelaProdutosCadastro extends javax.swing.JFrame {
    
    /**
     * Creates new form TelaBase
     */
        
    public TelaProdutosCadastro() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFundo = new javax.swing.JPanel();
        pnlBarraTitulo = new javax.swing.JPanel();
        btn_fechar = new javax.swing.JLabel();
        btn_minimizar = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnConcluir = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        srlDescricao = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        lblQuantidade = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFundo.setBackground(new java.awt.Color(255, 255, 255));
        pnlFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBarraTitulo.setBackground(new java.awt.Color(0, 85, 166));
        pnlBarraTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_fechar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        btn_fechar.setForeground(new java.awt.Color(255, 255, 255));
        btn_fechar.setText("X");
        btn_fechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_fecharMouseClicked(evt);
            }
        });
        pnlBarraTitulo.add(btn_fechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        btn_minimizar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        btn_minimizar.setForeground(new java.awt.Color(255, 255, 255));
        btn_minimizar.setText("_");
        btn_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizarMouseClicked(evt);
            }
        });
        pnlBarraTitulo.add(btn_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, -1));

        lbl_usuario.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_usuario.setText("Cadastro de produto");
        pnlBarraTitulo.add(lbl_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 40));

        pnlFundo.add(pnlBarraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        btnLimpar.setBackground(new java.awt.Color(0, 85, 166));
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimparMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimparMouseExited(evt);
            }
        });
        btnLimpar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Limpar");
        btnLimpar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 20));

        pnlFundo.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 90, 40));

        btnCancelar.setBackground(new java.awt.Color(0, 85, 166));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        btnCancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Cancelar");
        btnCancelar.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 20));

        pnlFundo.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 540, 90, 40));

        btnConcluir.setBackground(new java.awt.Color(0, 85, 166));
        btnConcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConcluirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConcluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConcluirMouseExited(evt);
            }
        });
        btnConcluir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Concluir");
        btnConcluir.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        pnlFundo.add(btnConcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 90, 40));

        lblNome.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(40, 40, 40));
        lblNome.setText("* Nome");
        pnlFundo.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        lblCategoria.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(40, 40, 40));
        lblCategoria.setText("* Categoria");
        pnlFundo.add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        lblMarca.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(40, 40, 40));
        lblMarca.setText("* Marca");
        pnlFundo.add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        lblModelo.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblModelo.setForeground(new java.awt.Color(40, 40, 40));
        lblModelo.setText("* Modelo");
        pnlFundo.add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        lblDescricao.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(40, 40, 40));
        lblDescricao.setText("Descrição");
        pnlFundo.add(lblDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        srlDescricao.setAutoscrolls(true);

        txtDescricao.setColumns(10);
        txtDescricao.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtDescricao.setForeground(new java.awt.Color(40, 40, 40));
        txtDescricao.setRows(5);
        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyTyped(evt);
            }
        });
        srlDescricao.setViewportView(txtDescricao);

        pnlFundo.add(srlDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 270, 100));

        lblQuantidade.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblQuantidade.setForeground(new java.awt.Color(40, 40, 40));
        lblQuantidade.setText("* Quantidade");
        pnlFundo.add(lblQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        lblValor.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblValor.setForeground(new java.awt.Color(40, 40, 40));
        lblValor.setText("* Valor");
        pnlFundo.add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        txtNome.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtNome.setForeground(new java.awt.Color(40, 40, 40));
        txtNome.setBorder(null);
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });
        pnlFundo.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 280, -1));

        txtMarca.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtMarca.setForeground(new java.awt.Color(40, 40, 40));
        txtMarca.setBorder(null);
        txtMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMarcaKeyTyped(evt);
            }
        });
        pnlFundo.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 180, -1));

        txtQuantidade.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtQuantidade.setForeground(new java.awt.Color(40, 40, 40));
        txtQuantidade.setBorder(null);
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyTyped(evt);
            }
        });
        pnlFundo.add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 180, -1));

        txtCategoria.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtCategoria.setForeground(new java.awt.Color(40, 40, 40));
        txtCategoria.setBorder(null);
        txtCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCategoriaKeyTyped(evt);
            }
        });
        pnlFundo.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 230, -1));

        txtModelo.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtModelo.setForeground(new java.awt.Color(40, 40, 40));
        txtModelo.setBorder(null);
        txtModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModeloKeyTyped(evt);
            }
        });
        pnlFundo.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 230, -1));

        txtValor.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtValor.setForeground(new java.awt.Color(40, 40, 40));
        txtValor.setBorder(null);
        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorKeyTyped(evt);
            }
        });
        pnlFundo.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 140, -1));
        pnlFundo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 280, 10));
        pnlFundo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 230, 10));
        pnlFundo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 180, 10));
        pnlFundo.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 230, 10));
        pnlFundo.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 180, 10));
        pnlFundo.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 140, 10));

        getContentPane().add(pnlFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConcluirMouseEntered
        setColor(btnConcluir);
    }//GEN-LAST:event_btnConcluirMouseEntered

    private void btnConcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConcluirMouseExited
        resetColor(btnConcluir);
    }//GEN-LAST:event_btnConcluirMouseExited

    private void btn_fecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_fecharMouseClicked
        
        //VOLTAR PARA A TELA PRODUTOS
        new TelaProdutos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_fecharMouseClicked

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        setColor(btnCancelar);
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        resetColor(btnCancelar);
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnConcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConcluirMouseClicked
           
        if (validaCamposVazios()) {
                        
            JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!");
            limpaCampos();
            //VOLTAR PARA A TELA PRODUTOS
            new TelaProdutos().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnConcluirMouseClicked

    private void btnLimparMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseEntered
        setColor(btnLimpar);
    }//GEN-LAST:event_btnLimparMouseEntered

    private void btnLimparMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseExited
        resetColor(btnLimpar);
    }//GEN-LAST:event_btnLimparMouseExited

    private void btnLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseClicked
        
        limpaCampos();

    }//GEN-LAST:event_btnLimparMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
    
        //VOLTAR PARA A TELA PRODUTOS
        TelaProdutos produto = new TelaProdutos();
        produto.show();
        this.dispose();        

    }//GEN-LAST:event_btnCancelarMouseClicked

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped

        //////////////////////////////////////////////// VALIDAÇÃO NOME
        if (txtNome.getText().length() < 30) {
            //verifica se foi digitado número
            if (txtNome.getText().matches("^[0-9].*")) {
                evt.consume();
                //caso tenha sido número, retorna que não é permitido número no campo
                JOptionPane.showMessageDialog(this, "Não é permitido números neste campo",
                    "Erro", JOptionPane.ERROR_MESSAGE);
                txtNome.setText("");
            }
            
        } else {
            //caso seja maior, estoura o limite de caracteres
            evt.consume();
            JOptionPane.showMessageDialog(this, "Limite de caractere em 30", "Erro", JOptionPane.ERROR_MESSAGE);
            txtNome.setText("");
            
        }
        
    }//GEN-LAST:event_txtNomeKeyTyped

    private void txtCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCategoriaKeyTyped

        //////////////////////////////////////////////// VALIDAÇÃO CATEGORIA
        if (txtCategoria.getText().length() < 15) {
            //verifica se foi digitado número
            if (txtCategoria.getText().matches("^[0-9].*")) {
                evt.consume();
                //caso tenha sido número, retorna que não é permitido número no campo
                JOptionPane.showMessageDialog(this, "Não é permitido números neste campo",
                    "Erro", JOptionPane.ERROR_MESSAGE);
                txtCategoria.setText("");
            }
            
        } else {
            //caso seja maior, estoura o limite de caracteres
            evt.consume();
            JOptionPane.showMessageDialog(this, "Limite de caractere em 15", "Erro", JOptionPane.ERROR_MESSAGE);
            txtCategoria.setText("");
            
        }

    }//GEN-LAST:event_txtCategoriaKeyTyped

    private void txtMarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMarcaKeyTyped

        //////////////////////////////////////////////// VALIDAÇÃO MARCA
        if (txtMarca.getText().length() < 20) {
            //verifica se foi digitado número
            if (txtMarca.getText().matches("^[0-9].*")) {
                evt.consume();
                //caso tenha sido número, retorna que não é permitido número no campo
                JOptionPane.showMessageDialog(this, "Não é permitido números neste campo",
                    "Erro", JOptionPane.ERROR_MESSAGE);
                txtMarca.setText("");
            }
            
        } else {
            //caso seja maior, estoura o limite de caracteres
            evt.consume();
            JOptionPane.showMessageDialog(this, "Limite de caractere em 20", "Erro", JOptionPane.ERROR_MESSAGE);
            txtMarca.setText("");
            
        }
        
    }//GEN-LAST:event_txtMarcaKeyTyped

    private void txtModeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModeloKeyTyped

        //////////////////////////////////////////////// VALIDAÇÃO MODELO
        if (txtModelo.getText().length() < 15) {
            //verifica se foi digitado número
            if (txtModelo.getText().matches("^[0-9].*")) {
                evt.consume();
                //caso tenha sido número, retorna que não é permitido número no campo
                JOptionPane.showMessageDialog(this, "Não é permitido números neste campo",
                    "Erro", JOptionPane.ERROR_MESSAGE);
                txtModelo.setText("");
            }
            
        } else {
            //caso seja maior, estoura o limite de caracteres
            evt.consume();
            JOptionPane.showMessageDialog(this, "Limite de caractere em 15", "Erro", JOptionPane.ERROR_MESSAGE);
            txtModelo.setText("");
            
        }

    }//GEN-LAST:event_txtModeloKeyTyped

    private void txtQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyTyped

        //////////////////////////////////////////////// VALIDAÇÃO QUANTIDADE
        if (txtQuantidade.getText().length() < 5) {
            
            String caracteres="0987654321";
            
            if(!caracteres.contains(evt.getKeyChar()+"")){
                evt.consume();
                
            }
            
        } else {
            //caso seja maior, estoura o limite de caracteres
            evt.consume();
            JOptionPane.showMessageDialog(this, "Limite de caractere em 5", "Erro", JOptionPane.ERROR_MESSAGE);
            txtQuantidade.setText("");
            
        }

    }//GEN-LAST:event_txtQuantidadeKeyTyped

    private void txtValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyTyped

        ///////////////////////////////////////////////// VALIDAÇÃO VALOR
        if (txtValor.getText().length() < 6) {
            
            String caracteres="0987654321";
            
            if(!caracteres.contains(evt.getKeyChar()+"")){
                evt.consume();
                
            }
            
        } else {
            //caso seja maior, estoura o limite de caracteres
            evt.consume();
            JOptionPane.showMessageDialog(this, "Limite de caractere em 6", "Erro", JOptionPane.ERROR_MESSAGE);
            txtValor.setText("");
            
        }
       

    }//GEN-LAST:event_txtValorKeyTyped

    private void txtDescricaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyTyped

        //////////////////////////////////////////////// VALIDAÇÃO DESCRIÇÃO
        if (txtDescricao.getText().length() < 250) {
           
            
        } else {
            //caso seja maior, estoura o limite de caracteres
            evt.consume();
            JOptionPane.showMessageDialog(this, "Limite de caractere em 250", "Erro", JOptionPane.ERROR_MESSAGE);
                        
        }

    }//GEN-LAST:event_txtDescricaoKeyTyped

    private void btn_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizarMouseClicked
        this.setState(1);
    }//GEN-LAST:event_btn_minimizarMouseClicked

    /**
     * @param args the command line arguments
     */
    
    
    //VALIDAÇÃO DE CAMPOS VAZIOS
    private boolean validaCamposVazios() {
        
        boolean status = true;
        
        if (this.txtNome.getText().equals("") || this.txtCategoria.getText().equals("") || this.txtMarca.getText().equals("") || this.txtModelo.getText().equals("") || this.txtQuantidade.equals("") ||
                this.txtValor.getText().equals("") || this.txtDescricao.getText().equals("")) {
            
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
            
            status = false;
            
        } else {
            
            status = true;

        }
        
        return status;
        
    }
   
    
    //LIMPA CAMPOS
    private void limpaCampos() {
        
        txtNome.setText("");
        txtCategoria.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtQuantidade.setText("");
        txtValor.setText("");
        txtDescricao.setText("");
        
    }
   
    
    //ALTERAR A COR DO OBJETO AO PASSAR O MOUSE
    public void setColor(JPanel panel){
    
        panel.setBackground(new java.awt.Color(40, 40, 40));
        
    }
    
    //VOLTAR PARA A COR PADRÃO DO OBJETO AO TIRAR O MOUSE DE CIMA
    public void resetColor(JPanel panel){
    
        panel.setBackground(new java.awt.Color(0, 85, 166));
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProdutosCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProdutosCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProdutosCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProdutosCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProdutosCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JPanel btnConcluir;
    private javax.swing.JPanel btnLimpar;
    private javax.swing.JLabel btn_fechar;
    private javax.swing.JLabel btn_minimizar;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JPanel pnlBarraTitulo;
    private javax.swing.JPanel pnlFundo;
    private javax.swing.JScrollPane srlDescricao;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
