package br.sp.senac.tads.views;

import br.sp.senac.tads.controller.ClienteController;
import br.sp.senac.tads.model.Cliente;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class TelaClientesCRUD extends javax.swing.JFrame {
    
    ClienteController clienteController = new ClienteController();
    Cliente clienteBean = new Cliente();
    String usuario_sessao;
    
    public TelaClientesCRUD() {
        initComponents();
        
    }
    
    public TelaClientesCRUD(String tipo, String sessao) {
        initComponents();
        lblTitulo.setText(tipo);
        this.usuario_sessao = sessao;
        setIcon(this);
        
        if (lblTitulo.getText().equals("Cadastrar")) {
            
            desativar();
            
        }
        
        if (lblTitulo.getText().equals("Editar")) {
            
            this.btnNovoCli.setVisible(false);
            this.lblNovoCliente.setVisible(false);
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdoGrupoEstCivil = new javax.swing.ButtonGroup();
        rdoGrupoSexo = new javax.swing.ButtonGroup();
        pnlFundo = new javax.swing.JPanel();
        pnlBarraTitulo = new javax.swing.JPanel();
        lblFechar = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnNovoCli = new javax.swing.JPanel();
        lblNovoCliente = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JPanel();
        lblLimpar = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JPanel();
        lblCancelar = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JPanel();
        lblCadastrar = new javax.swing.JLabel();
        pnlDadosPessoais = new javax.swing.JPanel();
        lblCodCliente = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblEstadoCivil = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        txtFormatCPF = new javax.swing.JFormattedTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblSexo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtFormatDtNasc = new javax.swing.JFormattedTextField();
        lblDataNascimento = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        cmbEstadoCivil = new javax.swing.JComboBox<>();
        cmbSexo = new javax.swing.JComboBox<>();
        lblID = new javax.swing.JLabel();
        pnlEndereco = new javax.swing.JPanel();
        lblLogradouro = new javax.swing.JLabel();
        txtFormatCEP = new javax.swing.JFormattedTextField();
        lblCEP = new javax.swing.JLabel();
        txtLogradouro = new javax.swing.JTextField();
        lblLogradouro1 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        pnlContato = new javax.swing.JPanel();
        lblTelefone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        txtFormatTelefone = new javax.swing.JFormattedTextField();
        txtFormatCelular = new javax.swing.JFormattedTextField();
        txtEmail = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFundo.setBackground(new java.awt.Color(255, 255, 255));
        pnlFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBarraTitulo.setBackground(new java.awt.Color(0, 85, 166));
        pnlBarraTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFechar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        lblFechar.setForeground(new java.awt.Color(255, 255, 255));
        lblFechar.setText("X");
        lblFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharMouseClicked(evt);
            }
        });
        pnlBarraTitulo.add(lblFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        lblMinimizar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        lblMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimizar.setText("_");
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });
        pnlBarraTitulo.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, -1));

        lblTitulo.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo.setText("lblTitulo");
        pnlBarraTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 40));

        pnlFundo.add(pnlBarraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        btnNovoCli.setBackground(new java.awt.Color(0, 85, 166));
        btnNovoCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovoCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoCliMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNovoCliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNovoCliMouseExited(evt);
            }
        });
        btnNovoCli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNovoCliente.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblNovoCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblNovoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNovoCliente.setText("Novo");
        lblNovoCliente.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnNovoCli.add(lblNovoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 20));

        pnlFundo.add(btnNovoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 90, 40));

        btnLimpar.setBackground(new java.awt.Color(0, 85, 166));
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLimparMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLimparMouseExited(evt);
            }
        });
        btnLimpar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLimpar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblLimpar.setForeground(new java.awt.Color(255, 255, 255));
        lblLimpar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLimpar.setText("Limpar");
        lblLimpar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnLimpar.add(lblLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 20));

        pnlFundo.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 90, 40));

        btnCancelar.setBackground(new java.awt.Color(0, 85, 166));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        btnCancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCancelar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblCancelar.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancelar.setText("Cancelar");
        lblCancelar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnCancelar.add(lblCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 20));

        pnlFundo.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 540, 90, 40));

        btnCadastrar.setBackground(new java.awt.Color(0, 85, 166));
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseExited(evt);
            }
        });
        btnCadastrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCadastrar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        lblCadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadastrar.setText("Concluir");
        lblCadastrar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnCadastrar.add(lblCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 20));

        pnlFundo.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 90, 40));

        pnlDadosPessoais.setBackground(new java.awt.Color(255, 255, 255));
        pnlDadosPessoais.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 40), 1, true), "Dados pessoais", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 0, 18))); // NOI18N
        pnlDadosPessoais.setForeground(new java.awt.Color(40, 40, 40));
        pnlDadosPessoais.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCodCliente.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblCodCliente.setText("--");
        pnlDadosPessoais.add(lblCodCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 50, -1));

        txtNome.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtNome.setForeground(new java.awt.Color(40, 40, 40));
        txtNome.setBorder(null);
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });
        pnlDadosPessoais.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 250, -1));
        pnlDadosPessoais.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 250, 10));

        lblEstadoCivil.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblEstadoCivil.setForeground(new java.awt.Color(40, 40, 40));
        lblEstadoCivil.setText("* Estado civil");
        pnlDadosPessoais.add(lblEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        lblCPF.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(40, 40, 40));
        lblCPF.setText("* CPF");
        pnlDadosPessoais.add(lblCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        txtFormatCPF.setBorder(null);
        txtFormatCPF.setForeground(new java.awt.Color(40, 40, 40));
        try {
            txtFormatCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFormatCPF.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        pnlDadosPessoais.add(txtFormatCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 160, -1));
        pnlDadosPessoais.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 160, 10));

        lblSexo.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblSexo.setText("* Sexo");
        pnlDadosPessoais.add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));
        pnlDadosPessoais.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 160, 10));

        txtFormatDtNasc.setBorder(null);
        txtFormatDtNasc.setForeground(new java.awt.Color(40, 40, 40));
        try {
            txtFormatDtNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFormatDtNasc.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        pnlDadosPessoais.add(txtFormatDtNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 160, -1));

        lblDataNascimento.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblDataNascimento.setForeground(new java.awt.Color(40, 40, 40));
        lblDataNascimento.setText("* Data de nascimento");
        pnlDadosPessoais.add(lblDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, -1));

        lblNome.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(40, 40, 40));
        lblNome.setText("* Nome");
        pnlDadosPessoais.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        cmbEstadoCivil.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cmbEstadoCivil.setForeground(new java.awt.Color(40, 40, 40));
        cmbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casado(a)", "Solteiro(a)", "Viuvo(a)", "Outro" }));
        cmbEstadoCivil.setSelectedItem(null);
        cmbEstadoCivil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlDadosPessoais.add(cmbEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 150, -1));

        cmbSexo.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cmbSexo.setForeground(new java.awt.Color(40, 40, 40));
        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino", "Outro" }));
        cmbSexo.setSelectedItem(null);
        cmbSexo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlDadosPessoais.add(cmbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 120, -1));

        lblID.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblID.setText("ID:");
        pnlDadosPessoais.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, -1, -1));

        pnlFundo.add(pnlDadosPessoais, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 780, 190));

        pnlEndereco.setBackground(new java.awt.Color(255, 255, 255));
        pnlEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 40), 1, true), "Endereço", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 0, 18))); // NOI18N
        pnlEndereco.setForeground(new java.awt.Color(40, 40, 40));
        pnlEndereco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogradouro.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblLogradouro.setForeground(new java.awt.Color(40, 40, 40));
        lblLogradouro.setText("Logradouro");
        pnlEndereco.add(lblLogradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        txtFormatCEP.setBorder(null);
        txtFormatCEP.setForeground(new java.awt.Color(40, 40, 40));
        try {
            txtFormatCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFormatCEP.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        pnlEndereco.add(txtFormatCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 150, -1));

        lblCEP.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblCEP.setForeground(new java.awt.Color(40, 40, 40));
        lblCEP.setText("CEP");
        pnlEndereco.add(lblCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        txtLogradouro.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtLogradouro.setForeground(new java.awt.Color(40, 40, 40));
        txtLogradouro.setBorder(null);
        txtLogradouro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLogradouroKeyTyped(evt);
            }
        });
        pnlEndereco.add(txtLogradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 320, -1));

        lblLogradouro1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblLogradouro1.setForeground(new java.awt.Color(40, 40, 40));
        lblLogradouro1.setText("Nº");
        pnlEndereco.add(lblLogradouro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, -1, -1));

        txtNumero.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtNumero.setForeground(new java.awt.Color(40, 40, 40));
        txtNumero.setBorder(null);
        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroKeyTyped(evt);
            }
        });
        pnlEndereco.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 90, -1));
        pnlEndereco.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 10));
        pnlEndereco.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 320, 10));
        pnlEndereco.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 90, 10));

        pnlFundo.add(pnlEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 780, 110));

        pnlContato.setBackground(new java.awt.Color(255, 255, 255));
        pnlContato.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 40), 1, true), "Contato", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 0, 18))); // NOI18N
        pnlContato.setForeground(new java.awt.Color(40, 40, 40));
        pnlContato.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTelefone.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(40, 40, 40));
        lblTelefone.setText("Telefone");
        pnlContato.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        lblEmail.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(40, 40, 40));
        lblEmail.setText("* E-mail");
        pnlContato.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        lblCelular.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblCelular.setForeground(new java.awt.Color(40, 40, 40));
        lblCelular.setText("Celular");
        pnlContato.add(lblCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        txtFormatTelefone.setBorder(null);
        txtFormatTelefone.setForeground(new java.awt.Color(40, 40, 40));
        try {
            txtFormatTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFormatTelefone.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        pnlContato.add(txtFormatTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 150, -1));

        txtFormatCelular.setBorder(null);
        txtFormatCelular.setForeground(new java.awt.Color(40, 40, 40));
        try {
            txtFormatCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFormatCelular.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        pnlContato.add(txtFormatCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 150, -1));

        txtEmail.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(40, 40, 40));
        txtEmail.setBorder(null);
        pnlContato.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 310, -1));
        pnlContato.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 10));
        pnlContato.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 150, 10));
        pnlContato.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 310, 10));

        pnlFundo.add(pnlContato, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 780, 110));

        getContentPane().add(pnlFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseEntered
        setColor(btnCadastrar);
    }//GEN-LAST:event_btnCadastrarMouseEntered

    private void btnCadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseExited
        resetColor(btnCadastrar);
    }//GEN-LAST:event_btnCadastrarMouseExited

    private void lblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseClicked
        //VOLTAR PARA A TELA CLIENTES
        new TelaClientes(usuario_sessao).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblFecharMouseClicked

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        setColor(btnCancelar);
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        resetColor(btnCancelar);
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        
        if (lblTitulo.getText().equals("Cadastrar")) {
            
            if (campoObrigatorio()) {
                
                clienteBean.setNomeCliente(txtNome.getText());
                clienteBean.setCPF(txtFormatCPF.getText().replaceAll("\\D", ""));
                clienteBean.setDataNascimento(txtFormatDtNasc.getText().replaceAll("\\D", ""));
                clienteBean.setEstadoCivil(cmbEstadoCivil.getSelectedItem().toString());
                clienteBean.setSexo(cmbSexo.getSelectedItem().toString());
                clienteBean.setCEP(txtFormatCEP.getText().replaceAll("\\D", ""));
                clienteBean.setLogradouro(txtLogradouro.getText());
                clienteBean.setNumero(txtNumero.getText());
                clienteBean.setTelefone(txtFormatTelefone.getText().replaceAll("\\D", ""));
                clienteBean.setCelular(txtFormatCelular.getText().replaceAll("\\D", ""));
                clienteBean.setEmail(txtEmail.getText());
                
                clienteController.cadastrarController(clienteBean);
                
                limparCampos();
                desativar();
                this.btnNovoCli.setEnabled(true);
                
            } else {
                
            }
            
        }
        
        if (lblTitulo.getText().equals("Editar")) {
            
            if (campoObrigatorio()) {
                
                clienteBean.setNomeCliente(txtNome.getText());
                clienteBean.setCPF(txtFormatCPF.getText().replaceAll("\\D", ""));
                clienteBean.setDataNascimento(txtFormatDtNasc.getText().replaceAll("\\D", ""));
                clienteBean.setEstadoCivil(cmbEstadoCivil.getSelectedItem().toString());
                clienteBean.setSexo(cmbSexo.getSelectedItem().toString());
                clienteBean.setCEP(txtFormatCEP.getText().replaceAll("\\D", ""));
                clienteBean.setLogradouro(txtLogradouro.getText());
                clienteBean.setNumero(txtNumero.getText());
                clienteBean.setTelefone(txtFormatTelefone.getText().replaceAll("\\D", ""));
                clienteBean.setCelular(txtFormatCelular.getText().replaceAll("\\D", ""));
                clienteBean.setEmail(txtEmail.getText());
                clienteBean.setId(Integer.parseInt(lblCodCliente.getText()));
                
                clienteController.alterarContrller(clienteBean);
                
                limparCampos();
                desativar();
                new TelaClientes(usuario_sessao).setVisible(true);
                this.dispose();
                
            } else {
                
            }
            
        }

    }//GEN-LAST:event_btnCadastrarMouseClicked

    private void btnLimparMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseEntered
        setColor(btnLimpar);
    }//GEN-LAST:event_btnLimparMouseEntered

    private void btnLimparMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseExited
        resetColor(btnLimpar);
    }//GEN-LAST:event_btnLimparMouseExited

    private void btnLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseClicked
        limparCampos();
    }//GEN-LAST:event_btnLimparMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked

        //VOLTAR PARA A TELA CLIENTES
        new TelaClientes(usuario_sessao).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnNovoCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoCliMouseClicked
        this.btnNovoCli.setEnabled(false);
        habilitar();
    }//GEN-LAST:event_btnNovoCliMouseClicked

    private void btnNovoCliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoCliMouseEntered
        setColor(btnNovoCli);
    }//GEN-LAST:event_btnNovoCliMouseEntered

    private void btnNovoCliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoCliMouseExited
        resetColor(btnNovoCli);
    }//GEN-LAST:event_btnNovoCliMouseExited

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
        // TODO add your handling code here:
        if (txtNome.getText().length() < 30) {
            //verifica se foi digitado o numero
            if (txtNome.getText().matches("^[0-9].*")) {
                evt.consume();
                //caso tenha sido numero retorna que não é permitido
                JOptionPane.showMessageDialog(this, "Permitido somente letras no campo \"Nome\"!", "Erro",
                        JOptionPane.ERROR_MESSAGE);
                txtNome.setText("");
            }
        } else {
            //caso seja maior estoura o limite
            evt.consume();
            JOptionPane.showMessageDialog(this, "Limite de até 30 caracteres!", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtNomeKeyTyped

    private void txtLogradouroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLogradouroKeyTyped
        // TODO add your handling code here:
        if (txtLogradouro.getText().length() < 30) {
            
        } else {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Limite de até 30 caracteres", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtLogradouroKeyTyped

    private void txtNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyTyped
        // TODO add your handling code here:
        if (txtNumero.getText().length() < 5) {
            String caracteres = "0987654321";
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        } else {
            //caso seja maior, estoura o limite de caracteres
            evt.consume();
            JOptionPane.showMessageDialog(this, "Limite de caractere em 5", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtNumeroKeyTyped

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        this.setState(1);
    }//GEN-LAST:event_lblMinimizarMouseClicked
    
    public void preencheCampos(Cliente beanCliente) {
        
        ArrayList<Cliente> listaCLiente = clienteController.consultarController(beanCliente);
        
        int i = 0;
        
        for (Object obj : listaCLiente) {
            Cliente cliente = (Cliente) obj;
            
            lblCodCliente.setText(Integer.toString(cliente.getId()));
            txtNome.setText(cliente.getNomeCliente());
            txtFormatCPF.setText(cliente.getCPF());
            txtFormatDtNasc.setText(cliente.getDataNascimento());
            cmbEstadoCivil.setSelectedItem(cliente.getEstadoCivil());
            cmbSexo.setSelectedItem(cliente.getSexo());
            txtFormatCEP.setText(cliente.getCEP());
            txtLogradouro.setText(cliente.getLogradouro());
            txtNumero.setText(cliente.getNumero());
            txtFormatTelefone.setText(cliente.getTelefone());
            txtFormatCelular.setText(cliente.getCelular());
            txtEmail.setText(cliente.getEmail());
            
            System.out.println(clienteBean.getDataNascimento());
            
            i++;
            
        }
        
    }
    
    public void setIcon(JFrame frm) {
        
        frm.setIconImage(Toolkit.getDefaultToolkit().getImage("src/main/resources/utilitarios/roupas.png"));
        
    }

    //ALTERAR A COR DO OBJETO AO PASSAR O MOUSE
    public void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(40, 40, 40));
    }

    //VOLTAR PARA A COR PADRÃO DO OBJETO AO TIRAR O MOUSE DE CIMA
    public void resetColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(0, 85, 166));
    }
    
    private void limparCampos() {
        txtEmail.setText("");
        txtLogradouro.setText("");
        txtFormatCPF.setText("");
        txtFormatCEP.setText("");
        txtFormatDtNasc.setText("");
        txtNome.setText("");
        txtNumero.setText("");
        rdoGrupoEstCivil.clearSelection();
        rdoGrupoSexo.clearSelection();
        txtFormatTelefone.setText("");
        txtFormatCelular.setText("");
        txtEmail.setText("");
        cmbEstadoCivil.setSelectedItem(null);
        cmbSexo.setSelectedItem(null);
        
    }
    
    private void desativar() {
        txtEmail.setEnabled(false);
        txtFormatCPF.setEnabled(false);
        txtFormatCEP.setEnabled(false);
        txtFormatDtNasc.setEnabled(false);
        txtFormatCelular.setEnabled(false);
        txtFormatTelefone.setEnabled(false);
        txtLogradouro.setEnabled(false);
        txtNome.setEnabled(false);
        txtNumero.setEnabled(false);
        btnCadastrar.setEnabled(false);
        btnLimpar.setEnabled(false);
        cmbEstadoCivil.setEnabled(false);
        cmbSexo.setEnabled(false);
    }
    
    private void habilitar() {
        txtEmail.setEnabled(true);
        txtFormatCPF.setEnabled(true);
        txtFormatCEP.setEnabled(true);
        txtFormatDtNasc.setEnabled(true);
        txtFormatCelular.setEnabled(true);
        txtFormatTelefone.setEnabled(true);
        txtLogradouro.setEnabled(true);
        txtNome.setEnabled(true);
        txtNumero.setEnabled(true);
        btnCadastrar.setEnabled(true);
        btnLimpar.setEnabled(true);
        cmbEstadoCivil.setEnabled(true);
        cmbSexo.setEnabled(true);
    }
    
    private boolean campoObrigatorio() {
        if (this.txtNome.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Campo \"Nome\" é obrigatório!");
            return false;
        }
        if (this.txtFormatCPF.getText().equals("   .   .   -  ")) {
            JOptionPane.showMessageDialog(this, "Campo \"CPF\" é obrigatório!");
            return false;
        }
        if (this.txtFormatDtNasc.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(this, "Campo \"Data de Nascimento\" é obrigatório!");
            return false;
        }
        if (this.cmbEstadoCivil.getSelectedItem() == "") {
            JOptionPane.showMessageDialog(this, "Campo \"Estado Civil\" é obrigatório!");
            return false;
        }
        if (this.cmbSexo.getSelectedItem() == "") {
            JOptionPane.showMessageDialog(this, "Campo \"Sexo\" é obrigatório!");
            return false;
        }
        if (this.txtEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo \"E-mail\" é obrigatório!");
            return false;
        }
        
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClientesCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClientesCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClientesCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClientesCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaClientesCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCadastrar;
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JPanel btnLimpar;
    private javax.swing.JPanel btnNovoCli;
    private javax.swing.JComboBox<String> cmbEstadoCivil;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCadastrar;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCodCliente;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblFechar;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLimpar;
    private javax.swing.JLabel lblLogradouro;
    private javax.swing.JLabel lblLogradouro1;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNovoCliente;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBarraTitulo;
    private javax.swing.JPanel pnlContato;
    private javax.swing.JPanel pnlDadosPessoais;
    private javax.swing.JPanel pnlEndereco;
    private javax.swing.JPanel pnlFundo;
    private javax.swing.ButtonGroup rdoGrupoEstCivil;
    private javax.swing.ButtonGroup rdoGrupoSexo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JFormattedTextField txtFormatCEP;
    private javax.swing.JFormattedTextField txtFormatCPF;
    private javax.swing.JFormattedTextField txtFormatCelular;
    private javax.swing.JFormattedTextField txtFormatDtNasc;
    private javax.swing.JFormattedTextField txtFormatTelefone;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
